services:

  postgres:
    image: postgres:15.10
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iwvgdevopsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - devopsNet

volumes:
  postgres_data:
    name: "postgres-data"

networks:
  devopsNet:
    external: true

# Start PostgreSQL
# docker compose -f docker-compose-db.yml -p databases up -d

# PostgreSQL console
# docker exec -it postgres psql -U postgres
# \?
# \l
# \connect <db> <usr>
# \dt
# \d <table>
# \q
# create database <db>;
# drop database <db>;
# select * from <table>;
# delete from <table>;