server:
  port: 8080

spring:
  application:
    name: iwvg-devops-lopez-robert
  profiles:
    default: dev
  output:
    ansi:
      enabled: ALWAYS
  cache:
    type: none
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    open-in-view: false

info:
  app:
    artifact: "@project.artifactId@"
    version: "@project.version@"
    build: "@maven.build.timestamp@"

app:
  hosting: localhost

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: true

logging:
  level:
    root: WARN
    es.upm.miw: DEBUG